# Alucard by Phantom
# Every value below is a colour from the official Dracula specification at
# https://spec.draculatheme.com, taken from its Alucard Classic tables.
# Dracula is (c) Dracula Theme, MIT licensed.

palette = 0=#fffbeb
palette = 1=#cb3a2a
palette = 2=#14710a
palette = 3=#846e15
palette = 4=#644ac9
palette = 5=#a3144d
palette = 6=#036a96
palette = 7=#1f1f1f
palette = 8=#6c664b
palette = 9=#d74c3d
palette = 10=#198d0c
palette = 11=#9e841a
palette = 12=#7862d0
palette = 13=#bf185a
palette = 14=#047fb4
palette = 15=#2c2b31

background = #fffbeb
foreground = #1f1f1f
bold-color = #2c2b31

cursor-color = #1f1f1f
cursor-text = #fffbeb

selection-background = #cfcfde
selection-foreground = #1f1f1f

split-divider-color = #cfcfde
unfocused-split-fill = #ceccc0

search-background = #846e15
search-foreground = #fffbeb
search-selected-background = #a34d14
search-selected-foreground = #fffbeb

window-titlebar-background = #ceccc0
window-titlebar-foreground = #1f1f1f

macos-icon-ghost-color = #644ac9
macos-icon-screen-color = #fffbeb
